name: Deploy to WordPress.org
on:
  workflow_run:
    workflows: ["Create release"]
    types:
      - completed

jobs:
  tag:
    name: New release

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Webpack Build
        run: |
          npm install
          npm run build

      - name: Composer Autoloader
        run: |
          composer install --no-dev --prefer-dist --no-progress 
          composer dump-autoload -o 

      - name: Get latest release tag
        id: get-latest-release
        uses: octokit/request-action@v2.x
        with:
          route: GET /repos/${{ github.repository }}/releases/latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract version number
        run: echo "VERSION=${{ fromJson(steps.get-latest-release.outputs.data).tag_name }}

      - name: WordPress Plugin Deploy
        id: deploy
        uses: 10up/action-wordpress-plugin-deploy@stable
        with:
          generate-zip: true
        env:
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SLUG: art-woocommerce-order-one-click
          VERSION: ${{ env.VERSION }}
